name: Docker Image CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.11.2-alpine

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install tox
        run: pip install tox==4.5.2

      - name: Run tox
        run: tox
